export const COLOR_BUTTON_PRIMARY = '#000000'
export const COLOR_BUTTON_PRIMARY_HOVER = '#808080'

export const COLOR_BUTTON_SECONDARY = '#FFFFFF'
export const COLOR_BUTTON_SECONDARY_HOVER = '#ECECEC'

export const COLOR_BACKGRAUND_NAVBAR = '#0A0E39'
export const COLOR_BACKGRAUND_SECCTION = '#E5E5EA'
export const COLOR_BACKGRAUND_CARD = '#FCFCFC'
